set -g default-terminal "screen-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Move between panes with Ctrl-a + Ctrl-hjkl
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# Set vi motions
setw -g mode-keys vi

# Setup
set -g status-bg 'black'
set -g status-fg 'white'
set -g status-right-length 80
set -g status-right '#(exec tmux ls| cut -d " " -f 1-3 |tr "\\n" "," )'

# Adjust status bar
set-option -g status-left-length 40
set-option -g status-left '#[fg=#white]#(echo "Session: ")#[fg=#white]#{session_name}'
set-option -g status-justify centre
set-option -g status-right '#(date)'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager 
run '~/.tmux/plugins/tpm/tpm'
