require('plugin_conf.setup.vimtex')
require('plugin_conf.setup.nvim-web-devicons')
require('plugin_conf.setup.nerdtree')
require('plugin_conf.setup.lsp')
require('plugin_conf.setup.mason')
require('plugin_conf.setup.colors')
require('plugin_conf.setup.barbar')
require('plugin_conf.setup.autopairs')
require('plugin_conf.setup.lualine')
require('plugin_conf.setup.semshi')
require('plugin_conf.setup.telescope')
require('plugin_conf.setup.toggleterm')
require('plugin_conf.setup.gitsigns')
require('plugin_conf.setup.nvim-ufo')
require('plugin_conf.setup.completions')
require('plugin_conf.setup.nvim-tree')
require('plugin_conf.setup.luasnip')


