require('config.setup.vimtex')
require('config.setup.nvim-web-devicons')
require('config.setup.mason')
require('config.setup.colors')
require('config.setup.barbar')
require('config.setup.lualine')
require('config.setup.telescope')
require('config.setup.toggleterm')
require('config.setup.gitsigns')
require('config.setup.completions')
require('config.setup.nvim-tree')
require('config.setup.treesitter')
require('config.setup.luasnip')

